export enum AuthKeys {
  FETCH_SIGNIN = 'FETCH_SIGNIN',
  SIGNOUT = 'SIGNOUT',
  FETCH_SIGNIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS',
  FETCH_SIGNIN_ERROR = 'FETCH_SIGNIN_ERROR',
  POST_SIGNUP = 'POST_SIGNUP',
  POST_SIGNUP_SUCCESS = 'POST_SIGNUP_SUCCESS',
}
